
AWSTemplateFormatVersion: "2010-09-09"
Description: "Template simplificado para estudo com VPC, Subnet, EC2, S3 e Lambda"

Resources:

  # ---------------- VPC ----------------
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: EstudoVPC

  # ---------------- Subnet ----------------
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: EstudoSubnet

  # ---------------- EC2 Instance ----------------
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-1234567890abcdef0  # Substitua por uma AMI válida se for testar
      InstanceType: t2.micro
      SubnetId: !Ref MySubnet
      Tags:
        - Key: Name
          Value: EstudoEC2

  # ---------------- S3 Bucket ----------------
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "estudo-bucket-${AWS::AccountId}"

  # ---------------- Lambda Function ----------------
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "EstudoLambda"
      Handler: index.handler
      Runtime: python3.9
      Role: arn:aws:iam::123456789012:role/EstudoLambdaRole  # Substitua pelo ARN real
      Code:
        ZipFile: |
          def handler(event, context):
              print("Olá do Lambda para estudo!")
